name: Contentful - weekly master backup
on:
    schedule:
        - cron: "30 15 * * 3"
    workflow_dispatch:

jobs:
    contentful_backup_job:
        runs-on: ubuntu-latest
        name: Contentful backup
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Back up Contentful environment
              uses: Jim-Horn/contentful-environment-backup@main
              id: backup
              with:
                  contentful-content-management-token: ${{secrets.CONTENTFUL_CONTENT_MANAGEMENT_TOKEN}}
                  contentful-space-id: "16nm6vz43ids"
                  backup-name-prefix: "master-backup"
                  delete-name-prefix: "master-backup"
