on:
  schedule:
    # 8PM UTC, Monday through Friday (12PM Central, 1PM Eastern)
    - cron: '0 18 * * 1-5'

jobs:
  contentful_backup_job:
    runs-on: ubuntu-latest
    name: Contentful backup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Back up Contentful environment
        uses: ./
        id: backup
        with:
          contentful-content-management-token: ${{secrets.CONTENTFUL_CONTENT_MANAGEMENT_TOKEN}}
