on:
  schedule:
    # 6PM UTC, Monday through Friday (12PM Central, 1PM Eastern)
    - cron: '0 18 * * 1-5'
    - cron: '0 9 * * 3'
    - cron: '2 9 * * 3'

jobs:
  contentful_backup_job:
    runs-on: ubuntu-latest
    name: Contentful backup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        uses: ./
      - name: Daily backup
        if: ${{ github.event.schedule == '0 18 * * 1-5' }}
        id: daily_backup
        with:
          contentful-content-management-token: ${{secrets.CONTENTFUL_CONTENT_MANAGEMENT_TOKEN}}
          contentful-space-id: "nrocpvfo0sk3"
          backup-name-prefix: "auto"
          delete-name-prefix: "auto"
        run: echo "running the daily backup"
      - name: Weekly master backup
        if: ${{ github.event.schedule == '0 9 * * 3' }}
        id: weekly_master_backup
        with:
          contentful-content-management-token: ${{secrets.CONTENTFUL_CONTENT_MANAGEMENT_TOKEN}}
          contentful-space-id: "nrocpvfo0sk3"
          backup-name-prefix: "weekly-master"
          delete-name-prefix: "weekly-master"
        run: echo "run weekly master backup"
      - name: Weekly release environment
        if: ${{ github.event.schedule == '2 9 * * 3' }}
        id: weekly_release_backup
        with:
          contentful-content-management-token: ${{secrets.CONTENTFUL_CONTENT_MANAGEMENT_TOKEN}}
          contentful-space-id: "nrocpvfo0sk3"
          backup-name-prefix: "weekly-release"
          delete-name-prefix: "weekly-release"
        run: echo "Weekly release environment"