on:
  schedule:
    # 6PM UTC, Monday through Friday (12PM Central, 1PM Eastern)
    - cron: '0 18 * * 1-5'
    - cron: '0 9 * * 3'
    - cron: '2 9 * * 3'

jobs:
  contentful_backup_job:
    runs-on: ubuntu-latest
    name: Contentful backup
    steps:
      - name: Daily backup
        if: ${{ github.event.schedule == '0 18 * * 1-5' }}
        run: echo "running the daily backup"
      - name: Weekly master backup environment
        if: ${{ github.event.schedule == '0 9 * * 3' }}
        run: echo "run weekly backup"
      - name: Weekly release environment
        if: ${{ github.event.schedule == '2 9 * * 3' }}
        run: echo "Weekly release environment"
